# Introduction

I read a lot a of books when I was a kid.  A **lot** of books.  My parents once, half-joking, said that they would have to punish me by taking away reading time since it was all I wanted to do.

I don't remember all the details of everything I read back then, but the writing infused the way I think and the way I see.  I can't tell you exactly where a lot of my thinking came from, but I would bet much of it was absorbed from all that reading.  

One of the joys of being parent is that I've gotten to re-read many of those same books again, and to be introduced to a whole new generation of children's writing.  Reading more consciously with my kids (and out loud!) I notice and remember more about them, and find new things to think about and find delight in. Literature that is aimed at children is filled with all the richness and complexity of adult literature, but it is expressed with directness and clarity.  And it communicates worldviews, ethics, critical thinking, care for others, and delight in the natural world more effectively than adult literature in part because its audience is undistracted, and in part because it is so direct.

This book is not aimed at children (though they are welcome to it!).  It is aimed at their parents. And it's not really a pleasure read (though I hope you enjoy it!)  This is an experiment.  It is an adult **activity book**, whose goal is to share a joy of reading and of thinking "around" children's stories, while picking up (or just practicing) some interesting skills.  It is also based on a theory of learning, drawn from my experience as a teacher and my reading of education research.  I can't claim that the ideas here are __new__, but I do hope that the particular combination of ideas is at least interesting to you.




But I should stop talking, and just give you an example:


Somehow I missed _Strega Nona_, by Tomie de Paola, when I was a kid.  It's old enough that I could have read it then, but somehow I didn't. I got to read it for the first time when my oldest child was two.  The story is a play on the trope of the Sorcerer's Apprentice (Die Zauberlehrling, by Goethe, the inspiration for the Disney film Fantasia).  The sorcerer is in the form of Strega Nona (Grandma Witch), an aging woman who lives in a town in Calabria, and the apprentice is in the form of Big Anthony, who takes a job doing chores for her.

One night, Big Anthony hears Strega Nona singing through the window of her little house.  He peeks inside just in time to see a black pasta pot that suddenly fills with steaming hot pasta.  Big Anthony then hears Strega Nona sing a different song, which makes the pot stop producing pasta.  "How wonderful!  That's a magic pasta pot for sure," he thinks.  But as he scurries around the house to hide his eavesdropping, he doesn't see Strega Nona blow three kisses to the pot to complete the spell (Foreshadowing! This knowledge will turn out to be pretty important!)


**I have so many questions.**

Did Strega Nona put water in the pot first? Is there a fire? Did she put the uncooked pasta in the pot herself? Or did it just appear, fully cooked? Where does the energy come from? How does she get the pasta to absorb the water faster than normal? Where does the water go afterward?

And now my wife and kids break in to shout, "What kind of a monster are you?  It's a **STORY**!"

And I haven't even gotten to the crazy parts yet!!

To me, turning an awesome children's story into a math problem enhances the story and the math, in the same way that understanding refraction affords a different mode of appreciation of the beauty of a rainbow.  Of course there are limits.  I don't want to ruin a good story by poking holes in it.  The point of this exercise isn't to find fault or to show how these authors were somehow wrong.  The idea is to have a bit of fun imagining "around" these stories, to learn a bit about a way of thinking that is potentially useful in understanding the "real world" while appreciating the art of these authors in a different way.

So sometimes I'm going to be satisfied to leave an odd bit in a story unexplained, or to put it in the "magic" box.  To quote another of my kids' favorites, _Phoebe and Her Unicorn_:  "MAGIC!!"

But now, let's do some activities to practice thinking "around" _Strega Nona_.

